server:
  port: 8002
spring:
  application:
    name: erya-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.165.193:3306/erya?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: YCH670989882@qq.com
    hikari:
      maximum-pool-size: 12
      minimum-idle: 6
  redis:
    jedis:
      pool:
        min-idle: 1
        max-idle: 2
        max-active: 2
#    host: 47.96.165.193
#    host: 134.175.99.101
    password: YCH670989882@qq.com
  task:
    execution:
      pool:
        core-size: 6
        queue-capacity: 200
        max-size: 12
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
#  cache:
#    type: redis
#    redis:
#      cache-null-values: false
#      time-to-live: 30d
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  rabbitmq:
    host: 47.96.165.193
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: user.pojo
logging:
  level:
    root: info
  path: /root/logs/erya
eureka:
  client:
    service‐url:
      defaultZone: http://127.0.0.1:8000/eureka
  instance:
    prefer‐ip‐address: true