spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/erya?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    password: YCH670989882@qq.com
    hikari:
      maximum-pool-size: 12
      minimum-idle: 6
  redis:
    jedis:
      pool:
        min-idle: 1
        max-idle: 2
        max-active: 2
  task:
    execution:
      pool:
        core-size: 6
        queue-capacity: 200
        max-size: 12
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 30d
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: cn.ych.erya.pojo
logging:
  level:
    root: info
  path: /root/logs/erya
