server:
  port: 8083
spring:
  application:
    name: erya-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.165.193:3306/erya?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    password: YCH670989882@qq.com
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
  redis:
    jedis:
      pool:
        min-idle: 1
        max-idle: 1
        max-active: 1
    host: 47.96.165.193
    password: YCH670989882@qq.com
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: admin.pojo
logging:
  level:
    root: info
  path: /root/logs/admin
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer‐ip‐address: true