server:
  port: 8081
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  tracker-list:            #TrackerList参数,支持多个
    - 134.175.99.101:22122
  pool:
    #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: -1
    #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 5000
    #每个key最大连接数
    max-total-per-key: 6
    #每个key对应的连接池最大空闲连接数
    max-idle-per-key: 2
    #每个key对应的连接池最小空闲连接数
    min_idle_per_key: 1
logging:
  level:
    root: info
  path: /root/logs/file
spring:
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB