server:
  port: 8004
spring:
  application:
    name: erya-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.96.54.89:3306/erya?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    password: YCH670989882@qq.com
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
  redis:
    jedis:
      pool:
        min-idle: 1
        max-idle: 1
        max-active: 1
#    host: 47.96.165.193
    host: 39.96.54.89
    password: YCH670989882@qq.com
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: admin.pojo
logging:
  level:
    root: info
  path: /root/logs/admin
eureka:
  client:
    service‐url:
      defaultZone: http://39.96.54.89:8000/eureka
  instance:
    prefer‐ip‐address: true
    ip-address: 134.175.99.101