server:
  port: 8004
spring:
  application:
    name: erya-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/erya?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    password: YCH670989882@qq.com
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
  redis:
    jedis:
      pool:
        min-idle: 1
        max-idle: 1
        max-active: 1
    password: YCH670989882@qq.com
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: YCH670989882@qq.com
        jdbc-url: jdbc:mysql://47.96.165.193:3306/erya?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: YCH670989882@qq.com
        jdbc-url: jdbc:mysql://134.175.99.101:3306/erya?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    masterslave:
      load-balance-algorithm-type: round_robin
      master-data-source-name: master
      slave-data-source-names: slave
      name: ms
    props:
      sql:
        show: false
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: admin.pojo
logging:
  level:
    root: info
  path: /root/logs/admin
eureka:
  client:
    service‐url:
      defaultZone: http://127.0.0.1:8000/eureka