server:
  port: 443
  ssl:
    key-store: classpath:api.erya.ychstudy.cn.pfx
    key-store-password: 5s876qfhtg0l
    key-store-type: PKCS12
# port:80
spring:
 application:
  name: erya-zuul #指定服务名
 mvc:
   throw-exception-if-no-handler-found: true
 resources:
   add-mappings: false
 redis:
   jedis:
     pool:
       min-idle: 1
       max-idle: 2
       max-active: 2
#   host: 47.96.165.193
   password: YCH670989882@qq.com
eureka:
  client:
    service‐url:
      defaultZone: http://127.0.0.1:8000/eureka
  instance:
    prefer‐ip‐address: true
zuul:
  routes:
    erya-user:
      path: /user/**
      serviceId: erya-user
    erya-admin:
      path: /admin/**
      serviceId: erya-admin
    erya-spider:
      path: /spider/**
      serviceId: erya-spider
    erya-auth:
      path: /auth/**
      serviceId: erya-auth
  host:
    connect-timeout-millis: 120000
    socket-timeout-millis: 300000
#hystrix:
#  metrics:
#    polling-interval-ms: 60000
ribbon:
  ReadTimeout: 100000  #请求处理的超时时间
  ConnectTimeout: 60000  #请求连接的超时时间