server:
  port: 8001
spring:
  application:
    name: erya-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.165.193:3306/erya?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    password: YCH670989882@qq.com
    hikari:
      maximum-pool-size: 12
      minimum-idle: 6
  redis:
    jedis:
      pool:
        min-idle: 1
        max-idle: 2
        max-active: 2
    host: 47.96.165.193
    password: YCH670989882@qq.com
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
#  cache:
#    type: redis
#    redis:
#      cache-null-values: false
#      time-to-live: 30d
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: auth.pojo
logging:
  level:
    root: info
  path: /root/logs/erya
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer‐ip‐address: true
jwt:
 config:
  key: erya
  ttl: 7200000