server:
  port: 8001
spring:
  application:
    name: erya-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/erya?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    password: YCH670989882@qq.com
    hikari:
      maximum-pool-size: 12
      minimum-idle: 6
  redis:
    jedis:
      pool:
        min-idle: 1
        max-idle: 20
        max-active: 20
#    host: 47.96.165.193
    password: YCH670989882@qq.com
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: auth.pojo
logging:
  level:
    root: info
  path: /root/logs/erya
eureka:
  client:
    service‐url:
      defaultZone: http://127.0.0.1:8000/eureka
  instance:
    prefer‐ip‐address: true
jwt:
 config:
  key: erya
  ttl: 21600000