server:
  port: 8004
spring:
  application:
    name: erya-spider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.165.193:3306/erya?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: YCH670989882@qq.com
    hikari:
      maximum-pool-size: 12
      minimum-idle: 6
  task:
    execution:
      pool:
        max-size: 12
        core-size: 12
        queue-capacity: 120
  rabbitmq:
    host: 47.96.165.193
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: spider.pojo
logging:
  level:
    root: info
  path: /root/logs/spider
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer‐ip‐address: true