server:
 port: 8086
spring:
 application:
  name: erya-zuul #指定服务名
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer‐ip‐address: true
zuul:
  routes:
    erya-user:
      path: /user/**
      serviceId: erya-user
    erya-admin:
      path: /admin/**
      serviceId: erya-admin
    erya-spider:
      path: /spider/**
      serviceId: erya-spider
    erya-auth:
      path: /auth/**
      serviceId: erya-auth